name: Waka Readme

on:
  schedule:
    - cron: '10 */12 * * *'
  workflow_dispatch: # for manual workflow trigger

jobs:
  update-readme:
    name: Waka - Readme
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.8
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          BLOCKS: ░▒▓█
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
