name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    name: waka-readme-stats
    runs-on: ubuntu-latest
    steps:
      - uses: miermontoto/waka-readme-stats@v5
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them 
          SHOW_TITLE: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          SHOW_COMMIT: true
          SHOW_LINES_OF_CODE: true
          LANG_COUNT: 10
