name: Waka Readme

on:
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC
  workflow_dispatch: # for manual workflow trigger

jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them 
          SHOW_TITLE: "True"
          SHOW_TIMEZONE: "True"
          SYMBOL_VERSION: 1
          TIME_RANGE: all_time
          SHOW_TIME: "True"
          SHOW_MASKED_TIME: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LINES_OF_CODE: "True"
          LANG_COUNT: 10
